[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.3.1"
solana-program = "1.18.1"


[lib]
name = "solana_calculator"
crate-type = ["cdylib", "lib"]


# solana cli -> solana-install init 1.17.19

